### ISSUE TITLE
getNftMetadata triggers NUMERIC_FAULT

### ISSUE THREAD

**Issue by perpetuum7** [alchemyplatform/alchemy-sdk-js#149]
### [REQUIRED] Environment

- Browser version: N/A (NodeJS 16.18.0)
- Alchemy SDK version: `^2.0.0`

### [REQUIRED] Describe the problem

There seems to be an error when the library attempts to construct a BigNumer in `getNftMetadata`.

```
2022-10-18T11:38:48.370800+00:00 app[worker.1]: /app/node_modules/alchemy-sdk/node_modules/@ethersproject/logger/lib/index.js:233
2022-10-18T11:38:48.370829+00:00 app[worker.1]: var error = new Error(message);
2022-10-18T11:38:48.370830+00:00 app[worker.1]: ^
2022-10-18T11:38:48.370830+00:00 app[worker.1]:
2022-10-18T11:38:48.370833+00:00 app[worker.1]: Error: overflow [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-overflow ] (fault="overflow", operation="BigNumber.from", value=3.824409351190545e+75, code=NUMERIC_FAULT, version=bignumber/5.6.2)
2022-10-18T11:38:48.370833+00:00 app[worker.1]: at Logger.makeError (/app/node_modules/alchemy-sdk/node_modules/@ethersproject/logger/lib/index.js:233:21)
2022-10-18T11:38:48.370834+00:00 app[worker.1]: at Logger.throwError (/app/node_modules/alchemy-sdk/node_modules/@ethersproject/logger/lib/index.js:242:20)
2022-10-18T11:38:48.370834+00:00 app[worker.1]: at throwFault (/app/node_modules/alchemy-sdk/node_modules/@ethersproject/bignumber/lib/bignumber.js:303:19)
2022-10-18T11:38:48.370835+00:00 app[worker.1]: at Function.BigNumber.from (/app/node_modules/alchemy-sdk/node_modules/@ethersproject/bignumber/lib/bignumber.js:206:17)
2022-10-18T11:38:48.370850+00:00 app[worker.1]: at NftNamespace.<anonymous> (/app/node_modules/alchemy-sdk/dist/cjs/index-04a23af4.js:611:46)
2022-10-18T11:38:48.370850+00:00 app[worker.1]: at Generator.next (<anonymous>)
2022-10-18T11:38:48.370851+00:00 app[worker.1]: at /app/node_modules/alchemy-sdk/dist/cjs/index-04a23af4.js:108:71
2022-10-18T11:38:48.370851+00:00 app[worker.1]: at new Promise (<anonymous>)
2022-10-18T11:38:48.370852+00:00 app[worker.1]: at __awaiter (/app/node_modules/alchemy-sdk/dist/cjs/index-04a23af4.js:104:12)
2022-10-18T11:38:48.370852+00:00 app[worker.1]: at NftNamespace.getNftMetadata (/app/node_modules/alchemy-sdk/dist/cjs/index-04a23af4.js:608:16) {
2022-10-18T11:38:48.370852+00:00 app[worker.1]: reason: 'overflow',
2022-10-18T11:38:48.370853+00:00 app[worker.1]: code: 'NUMERIC_FAULT',
2022-10-18T11:38:48.370853+00:00 app[worker.1]: fault: 'overflow',
2022-10-18T11:38:48.370854+00:00 app[worker.1]: operation: 'BigNumber.from',
2022-10-18T11:38:48.370854+00:00 app[worker.1]: value: 3.824409351190545e+75
2022-10-18T11:38:48.370854+00:00 app[worker.1]: }
```

#### How to reproduce:

It happened whilst tracking sales for the ENS asset.

#### Relevant code or sample repro:

https://github.com/KodexLabs/ethereum-nft-sales-bot

**Comment by thebrianchen** [comment]
@perpetuum7 Thanks for filing this issue! Will add a fix to return the value as an integer string if it overflows in BigNumber.

**Comment by thebrianchen** [comment]
@perpetuum7 Can you provide the NFT address for the call that is failing? I'm having trouble finding a repro. Thanks!

**Comment by thebrianchen** [comment]
Marking the issue as closed, as this seems to be an issue with incorrect input to the method params.
