### ISSUE TITLE
Cannot find variable atob

### ISSUE THREAD

**Issue by Jake-Mulhern** [alchemyplatform/alchemy-sdk-js#166]
### [REQUIRED] Environment

- Browser version: Chrome

- Alchemy SDK version: 2.2.0

### [REQUIRED] Describe the problem:
Whenever I try to import Alchemy from 'alchemy-sdk' I get the error stating that the variable 'atob' cannot be found.

#### How to reproduce:
In the terminal:
$ yarn add achemy-sdk
$ yarn

In the code:
import { Alchemy} from 'alchemy-sdk'

Etc:
Run project in expo

Receive error message

#### Relevant code or sample repro:

ReferenceError: Can't find variable: atob
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:17 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:39 in handleError
at node_modules/expo/build/errors/ExpoErrorManager.js:25:19 in errorHandler
at node_modules/expo/build/errors/ExpoErrorManager.js:30:24 in <anonymous>
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0

**Comment by thebrianchen** [comment]
@Jake-Mulhern Do you have a more detailed stack trace of where `atob` is required by the SDK?

I'm seeing other issues in other libraries where `atob` and `btoa` are not part of the global namespace in react-native (see SO post).

Let me know if this workaround does the trick for you: 
```
npm install base-64
```
Then in your app entry file:
```js
import {decode, encode} from 'base-64';
if (!global.btoa) { 
  global.btoa = encode;
} 
if (!global.atob) { 
  global.atob = decode; 
}
```

**Comment by Jake-Mulhern** [comment]
@thebrianchen I managed to fix this by importing both of these before importing 'alchemy-sdk'

import 'react-native-get-random-values';
import '@ethersproject/shims';

import {Alchemy} from 'alchemy-sdk';
