### ISSUE TITLE
Error while backfilling "newHeads" subscription

### ISSUE THREAD

**Issue by ProTrader69** [alchemyplatform/alchemy-sdk-js#169]
### [REQUIRED] Environment

Alchemy SDK, Node JS

- Browser version:
- Alchemy SDK version: alchemy-sdk@2.1.1

### [REQUIRED] Describe the problem

Alchemy SDK hangs after an internal exception during websocket "blocks" subscription event. The SDK tries to convert a non BigNumber value to BigNumber and crashes at Object.fromHex (.../node_modules/alchemy-sdk/dist/cjs/index-7d6928ec.js:229:32). After this crash, websocket subscriptions won't get any new events.

#### How to reproduce:

Subscribe to new "blocks" subscription (alchemy.ws.on("block", (blockNumber)) using alchemy SDK. New block events will be received normally as expected till it receives a server response with non hexadecimal/number value. In my experience this event occurs at least once every 12 hours.

#### Relevant code or sample repro:

Code: 
```
alchemy.ws.on("block", (blockNumber) => {
    try {
      if (blockNumber != undefined) {
        latestBlockNumber = Number(blockNumber);
      }
    } catch (error) {
      console.log("block err: ", error.toString());
    }
  });
```
  
  Stack:
```
Error while backfilling "newHeads" subscription. Some events may be missing. Error: invalid BigNumber value (argument="value", value=undefined, code=INVALID_ARGUMENT, version=bignumber/5.7.0)
at Logger.makeError (/var/app/current/node_modules/@ethersproject/logger/lib/index.js:238:21)
at Logger.throwError (/var/app/current/node_modules/@ethersproject/logger/lib/index.js:247:20)
at Logger.throwArgumentError (/var/app/current/node_modules/@ethersproject/logger/lib/index.js:250:21)
at Function.BigNumber.from (/var/app/current/node_modules/@ethersproject/bignumber/lib/bignumber.js:239:23)
at Object.fromHex (/var/app/current/node_modules/alchemy-sdk/dist/cjs/index-7d6928ec.js:229:32)
at getNewHeadsBlockNumber (/var/app/current/node_modules/alchemy-sdk/dist/cjs/alchemy-websocket-provider-94a351b4.js:1251:18)
at addToPastEventsBuffer (/var/app/current/node_modules/alchemy-sdk/dist/cjs/alchemy-websocket-provider-94a351b4.js:1274:32)
at AlchemyWebSocketProvider.rememberEvent (/var/app/current/node_modules/alchemy-sdk/dist/cjs/alchemy-websocket-provider-94a351b4.js:1002:9)
at AlchemyWebSocketProvider.emitAndRememberEvent (/var/app/current/node_modules/alchemy-sdk/dist/cjs/alchemy-websocket-provider-94a351b4.js:986:14)
at AlchemyWebSocketProvider.emitNewHeadsEvent (/var/app/current/node_modules/alchemy-sdk/dist/cjs/alchemy-websocket-provider-94a351b4.js:972:14)
at /var/app/current/node_modules/alchemy-sdk/dist/cjs/alchemy-websocket-provider-94a351b4.js:949:54
at Array.forEach (<anonymous>)
at AlchemyWebSocketProvider.<anonymous> (/var/app/current/node_modules/alchemy-sdk/dist/cjs/alchemy-websocket-provider-94a351b4.js:949:32)
at Generator.next (<anonymous>)
at fulfilled (/var/app/current/node_modules/alchemy-sdk/dist/cjs/index-7d6928ec.js:175:58)
at runMicrotasks (<anonymous>) {
reason: 'invalid BigNumber value',
code: 'INVALID_ARGUMENT',
argument: 'value',
value: undefined
}

```

**Comment by thebrianchen** [comment]
@ProTrader69 Thanks for sharing the full error message. Does the error occur only during backfill, or during the standard websocket messages as well? I'll try reproducing this error sometime next week to get some more details on the underlying event and why the field is `undefined`.

**Comment by ProTrader69** [comment]
> @ProTrader69 Thanks for sharing the full error message. Does the error occur only during backfill, or during the standard websocket messages as well? I'll try reproducing this error sometime next week to get some more details on the underlying event and why the field is `undefined`.

This happens during the standard websocket message listening.
