### ISSUE TITLE
`getNftsForOwner` fails for some tokens with no token ID

### ISSUE THREAD

**Issue by sds** [alchemyplatform/alchemy-sdk-js#191]
Hello! Not sure if this is a backend issue or an issue with this SDK, but posting here since the SDK is where we're seeing the error.

If there's a better place, happy to move this elsewhere.

### Environment

Alchemy SDK version: 2.2.1

### Describe the problem

For certain wallet addresses, the `getNftsForOwner` call fails. If this is user error, a more helpful error related to the cause of the issue would help. This error appears to be due to token metadata not being available.

#### How to reproduce:

Run the following:
```ts
import { Alchemy, Network } from 'alchemy-sdk';

const alchemy = new Alchemy({
  apiKey: '...',
  network: Network.ETH_MAINNET,
});
alchemy.nft.getNftsForOwner('0x477c2087f3d6e49b1be5c790a33b3a025a4fa569')
```

...which results in the following error:

```
Error: invalid BigNumber value (argument="value", value=undefined, code=INVALID_ARGUMENT, version=bignumber/5.7.0)
    at Logger.makeError (...node_modules/alchemy-sdk/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (...node_modules/alchemy-sdk/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at Logger.throwArgumentError (...node_modules/alchemy-sdk/node_modules/@ethersproject/logger/src.ts/index.ts:285:21)
    at Function.BigNumber.from (...node_modules/alchemy-sdk/node_modules/@ethersproject/bignumber/src.ts/bignumber.ts:289:23)
    at parseNftTokenId (...node_modules/alchemy-sdk/src/util/util.ts:131:20)
    at getNftFromRaw (...node_modules/alchemy-sdk/src/util/util.ts:105:14)
    at nftFromGetNftResponse (...node_modules/alchemy-sdk/src/internal/nft-api.ts:485:10)
    at getNftsForOwnerIterator_1 (...node_modules/alchemy-sdk/src/internal/nft-api.ts:122:4)
    at getNftsForOwnerIterator_1.next (<anonymous>)
    at resume (...node_modules/alchemy-sdk/dist/cjs/index-53a13ded.js:245:44) {
  reason: 'invalid BigNumber value',
  code: 'INVALID_ARGUMENT',
  argument: 'value',
  value: undefined
}
```

**Comment by thebrianchen** [comment]
@sds This is an issue with our backend's ingestion since the token id should always be defined. I'll post a follow up on this issue after checking with our team.

**Comment by thebrianchen** [comment]
@sds Sorry for the inconvenience. I added better error messaging, and the metadata ingestion has been fixed.

**Comment by sds** [comment]
Thanks for the investigation and quick fix!

**Comment by sds** [comment]
A heads up @thebrianchen: we're seeing this error a lot more now. Has the issue with the metadata ingestion been resolved? Here are some more addresses where the problem occurs:

```
0x0734d56da60852a03e2aafae8a36ffd8c12b32f1
0xA6c0F7bde119930fB919ed02F8155887EcF0D756
0xf296178d553c8ec21a2fbd2c5dda8ca9ac905a00
0x3a6372B2013f9876a84761187d933DEe0653E377
0x5164cf3b0c8c0fdfe4bcc9cf4f1e8f7e39461a59
0xa1f8cdbf38e2acafbc5f0fbfe1ca9446d5988841
```
