### ISSUE TITLE
lchemySubscription.PENDING_TRANSACTIONS, fromAddress/toAddress can not use string[]

### ISSUE THREAD

**Issue by zfqz** [alchemyplatform/alchemy-sdk-js#222]
### [REQUIRED] Environment

- Browser version:
- Alchemy SDK version: 2.2.5

-----------------------------------------------------------
```
const settings = {
  apiKey: "xxxx", // Replace with your Alchemy API Key.
  network: Network.ETH_MAINNET,
};

const alchemy = new Alchemy(settings);

const followArray: string[] = [
  "0xde29d060d45901fb19ed6c6e959eb22d8626708e",
  "0xf25A027b01ec26AFdAb45963794007A91Aad9838",
];

// Subscription for Alchemy's pendingTransactions API
alchemy.ws.on(
  {
    method: AlchemySubscription.PENDING_TRANSACTIONS,
    toAddress: followArray,
  },
  (tx) => console.log(tx)
);
```

-----------------------------------------------------------
error:
```
F:\xxxx\node_modules\alchemy-sdk\dist\cjs\index-e8114eb4.js:276
    return new (P || (P = Promise))(function (resolve, reject) {
           ^
TypeError: Cannot read properties of undefined (reading 'config')
    at F:\xxxx\node_modules\alchemy-sdk\src\api\websocket-namespace.ts:194:33
    at Generator.next (<anonymous>)
    at F:\xxxx\node_modules\alchemy-sdk\dist\cjs\index-e8114eb4.js:280:71
    at new Promise (<anonymous>)
    at __awaiter (F:\xxxx\node_modules\alchemy-sdk\dist\cjs\index-e8114eb4.js:276:12)
    at _resolveNameOrError (F:\xxxx\node_modules\alchemy-sdk\dist\cjs\index-e8114eb4.js:2961:16)
    at Array.map (<anonymous>)
    at WebSocketNamespace.<anonymous> (F:\xxxx\node_modules\alchemy-sdk\src\api\websocket-namespace.ts:176:33)
    at Generator.next (<anonymous>)
    at F:\xxxx\node_modules\alchemy-sdk\dist\cjs\index-e8114eb4.js:280:71
```

**Comment by zfqz** [comment]
![image](https://user-images.githubusercontent.com/95525934/208818004-ee98197a-ad27-4d92-a443-50eeb5bd04ee.png)
error is here,
i solve it, when i delete .map(this._resolveNameOrError));

**Comment by thebrianchen** [comment]
@zfqz Thanks for catching this issue! Should have a fix out this week.
