### ISSUE TITLE
Nuxt 3 - Cannot find module './api/utils'

### ISSUE THREAD

**Issue by joshuk** [alchemyplatform/alchemy-sdk-js#242]
### Environment

- Browser version: Node v16.14.2
- Alchemy SDK version: 2.3.0

### Describe the problem

When importing the Alchemy SDK module in a Nuxt 3 project, you're given the following error:
```
Cannot find module './api/utils'

at Function.Module._load (node:internal/modules/cjs/loader:778:27)
at Module.require (node:internal/modules/cjs/loader:1005:19)
at require (node:internal/modules/cjs/helpers:102:18)
at ./alchemy-sdk:5:13
at ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:285:11)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:146:14)
at async request (./node_modules/vite-node/dist/client.mjs:172:16)
```

#### How to reproduce:

1. Create a blank Nuxt 3 environment (either locally or using something like [StackBlitz](https://stackblitz.com/))
2. Run `npm install alchemy-sdk`
3. Open app.js, add the following below the `<template>`:
```
<script>
import { Network, Alchemy } from 'alchemy-sdk';
</script>
```

**Comment by thebrianchen** [comment]
@joshuk I played around with it a bit, and I was able to repro the issue and fix it on stackblitz. Starting with a fresh nuxt.js project (which has the error), I modified the `nuxt.config.ts` file to be the following:

```
export default defineNuxtConfig({
  build: {
    transpile: ['alchemy-sdk'],
  },
});
```

Adding the `transpile` property made the error go away. The `Utils` in the SDK are exported in a similar manner to the way ethers exports its `utils`, so the Github [issue](https://github.com/ethers-io/ethers.js/issues/1784) helped resolve the error.

I'm going to mark this issue as closed but feel free to ask any other questions you may have!
