### ISSUE TITLE
`getMintedNfts` throws error `this endpoint only supports up to 100 tokens per request`

### ISSUE THREAD

**Issue by gstsdev** [alchemyplatform/alchemy-sdk-js#318]
### [REQUIRED] Environment

- Browser version:
- Alchemy SDK version: 2.6.0, 2.8.2

### [REQUIRED] Describe the problem

Sometimes `getMintedNfts` will throw the following error:

```
Error: 400: Sorry, this endpoint only supports up to 100 tokens per request.
    at /Users/gustavosampaio/Sources/layer/layer-web/packages/sdk/node_modules/alchemy-sdk/dist/cjs/index-e34d13a5.js:2173:29
    at Generator.throw (<anonymous>)
    at rejected (/Users/gustavosampaio/Sources/layer/layer-web/packages/sdk/node_modules/alchemy-sdk/dist/cjs/index-e34d13a5.js:394:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Specifically, this happens when paginating `getMintedNfts` results (sequentially passing the `pageKey` returned in the previous response).

I tried to debug Alchemy's code and noticed it would get a response with 101 tokens, [despite the `maxCount` parameter being set to `100`](https://github.com/alchemyplatform/alchemy-sdk-js/blob/c18e12bab9707424f029d3ff3303528d74ca6f9b/src/internal/nft-api.ts#L372):

<img width="1391" alt="alchemy-screenshot-2" src="https://user-images.githubusercontent.com/37808461/236241926-21f703f7-a2cb-48fd-a41d-0f1ceb3b2a0c.png">

<img width="1391" alt="alchemy-screenshot-3" src="https://user-images.githubusercontent.com/37808461/236240449-e456a38f-2130-418e-900c-4ed64a0750d6.png">

#### How to reproduce:

```javascript
const { Alchemy } = require("alchemy-sdk");

const alchemy = new Alchemy({ apiKey: ALCHEMY_API_KEY });

async function paginate(request) {
  let pageKey,
    nfts = [];
  do {
    const response = await request(pageKey);
    pageKey = response.pageKey;
    nfts.push(...response.nfts);
  } while (pageKey);
  return nfts;
}

paginate(async (pageKey) => {
  try {
    return await alchemy.nft.getMintedNfts(
      ADDRESS_WITH_MANY_NFTS,
      {
        pageKey,
      }
    );
  } catch (err) {
    console.log(err.stack);
    throw err;
  }
}).then((nfts) => {
  console.log(nfts);
});
```

**Comment by thebrianchen** [comment]
@gstsdev thanks for catching this! I'd like to try and repro this on my end. Can you share the address you were using that triggered this?

**Comment by gstsdev** [comment]
> @gstsdev thanks for catching this! I'd like to try and repro this on my end. Can you share the address you were using that triggered this?

Sure. It's this one: `0x1e8E749b2B578E181Ca01962e9448006772b24a2`
