### ISSUE TITLE
`getTokensForOwner` throws invalid BigNumber exception for some tokens

### ISSUE THREAD

**Issue by mholtzman** [alchemyplatform/alchemy-sdk-js#319]
### [REQUIRED] Environment

- Browser version:
- Alchemy SDK version: 2.8.2

### [REQUIRED] Describe the problem

A simple call to `getTokensForOwner()` for some users throws an error. I've noticed this type of exception myself in the past when working with ethers.js if trying to parse a response from a contract call that's expected to return a value but instead returns `0x`. Note that the call works fine for other accounts.

Exception:
```
Error: invalid BigNumber string (argument="value", value="0x", code=INVALID_ARGUMENT, version=bignumber/5.7.0)
    at Logger.makeError (/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at Logger.throwArgumentError (/node_modules/@ethersproject/logger/lib/index.js:250:21)
    at BigNumber.from (/node_modules/@ethersproject/bignumber/lib/bignumber.js:199:27)
    at /node_modules/alchemy-sdk/dist/cjs/index-25500d2e.js:1817:49
    at Array.map (<anonymous>)
    at CoreNamespace.<anonymous> (/node_modules/alchemy-sdk/dist/cjs/index-25500d2e.js:1815:62)
    at Generator.next (<anonymous>)
    at fulfilled (/node_modules/alchemy-sdk/dist/cjs/index-25500d2e.js:399:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  reason: 'invalid BigNumber string',
  code: 'INVALID_ARGUMENT',
  argument: 'value',
  value: '0x'
}
```
#### How to reproduce:

Sample script:
```
import {
  Alchemy,
  Network
} from 'alchemy-sdk'

const settings = {
  network: Network.Mainnet,
  apiKey: '<my_api_key>'
}

const sdk = new Alchemy(settings)

sdk.core.getTokensForOwner('<address>').then(console.log)
```

**Comment by thebrianchen** [comment]
@mholtzman Thanks for the report! Can you share a sample address for me to repro this on my end?
